Repository CS2103JAN2018-W15-B4/main, pull requests merged in 2018-03, with the labels that each got.

#51 Add User Stories
  docs/DeveloperGuide.adoc
Labels: status.readyToMerge, type.Documentation

#47 Update target user profile
  docs/DeveloperGuide.adoc
Labels: status.Ongoing, type.Documentation

#53 Add use cases
  docs/DeveloperGuide.adoc
Labels: type.Documentation

#61 Add NFRs
  docs/DeveloperGuide.adoc
Labels: type.Documentation

#60 Product Scope - Target User Profile + Value Proposition
  docs/DeveloperGuide.adoc
Labels: status.readyToMerge, type.Documentation

#59 ReadMe - Product Description
  README.adoc
Labels: status.readyToMerge, type.Documentation

#63 Update app name
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.Documentation

#66 Group field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: enhancement, priority.high, type.Code

#67 Replace address to matric number
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/MatricNumber.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/MatricNumberTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: type.Code

#68 Add Remove tag command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/model/tag/exceptions/TagNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
  src/test/java/seedu/address/logic/parser/RemoveTagCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: enhancement, needsDocumentation, priority.high, status.readyForReview, type.Code

#69 removegroup Command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/RemoveGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveGroupCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/exceptions/GroupCannotBeRemovedException.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemoveGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/RemoveGroupCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/systemtests/RemoveGroupCommandSystemTest.java
Labels: priority.high, status.readyToMerge, type.Code

#71 Update UserGuide and DeveloperGuide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.Documentation

#73 Update Codacy badge
  README.adoc
Labels: status.readyToMerge, type.Documentation

#76 Change icon
  copyright.txt
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/club_connect_256.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.medium, status.readyForReview, type.Code

#77 Add Delete tag tests
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/systemtests/DeleteTagCommandSystemTest.java
Labels: priority.high, status.readyForReview, type.Code, type.Documentation

#74 Add Findby command
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindByCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindByCommandParser.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/FindByCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/FieldContainsKeywordsPredicateTest.java
Labels: enhancement, status.done, type.Code

#79 Add Coming in v2.0
  docs/UserGuide.adoc
Labels: status.readyToMerge, type.Documentation

#81 Display Group Attribute in UI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: status.done, type.UI

#80 Change UI pic
  docs/images/Ui.png
Labels: status.readyToMerge, type.Documentation

#83 Remove learning outcomes
  README.adoc
Labels: status.readyToMerge, type.Documentation

#82 Update AboutUs.adoc
  docs/AboutUs.adoc
  docs/images/amrut-prabhu.png
  docs/images/muhdnurkamal.png
  docs/images/th14thmusician.png
  docs/images/yash-chowdhary.png
Labels: status.done, status.readyForReview, type.Documentation

#78 Implement LogIn function
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LogInCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Password.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/Username.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: enhancement, priority.high

#96 Update Developer Guide
  docs/DeveloperGuide.adoc
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/DeletePersonSdForLogic.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SDforDeletePerson.png
  docs/images/SDforDeletePersonEventHandling.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.high, type.Documentation

#95 User Guide updates
  clubbook.xml
  docs/UserGuide.adoc
  docs/images/help-window.png
  docs/stylesheets/asciidoctor.css
Labels: priority.high, status.readyForReview, type.Documentation

#99 Feature Contribution
  docs/DeveloperGuide.adoc
Labels: status.readyToMerge, type.Documentation

#102 Update ContactUs
  docs/ContactUs.adoc
Labels: status.readyToMerge, type.Documentation

#101 Tests
  src/test/java/seedu/club/logic/commands/CommandTestUtil.java
  src/test/java/seedu/club/model/group/GroupTest.java
  src/test/java/seedu/club/model/member/EmailTest.java
  src/test/java/seedu/club/model/member/MatricNumberTest.java
  src/test/java/seedu/club/model/member/NameTest.java
  src/test/java/seedu/club/model/member/PhoneTest.java
Labels: status.readyToMerge

#103 Add compress and decompress commands
  src/main/java/seedu/club/commons/events/ui/CompressMembersRequestEvent.java
  src/main/java/seedu/club/commons/events/ui/DecompressMembersRequestEvent.java
  src/main/java/seedu/club/logic/commands/CompressCommand.java
  src/main/java/seedu/club/logic/commands/DecompressCommand.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/ui/CompressedMemberCard.java
  src/main/java/seedu/club/ui/MemberCard.java
  src/main/java/seedu/club/ui/MemberListPanel.java
  src/main/resources/view/CompressedMemberListCard.fxml
  src/test/java/seedu/club/logic/commands/CompressCommandTest.java
  src/test/java/seedu/club/logic/commands/DecompressCommandTest.java
  src/test/java/seedu/club/logic/parser/ClubBookParserTest.java
  src/test/java/seedu/club/ui/MemberListPanelTest.java
Labels: enhancement, priority.high, status.readyForReview, type.Code, type.UI

#97 #90 Implement auto sort
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/member/UniqueMemberList.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.medium, status.readyToMerge, type.Code

#98 Update developer guide
  docs/DeveloperGuide.adoc
  docs/diagrams/UndoRedoExecuteUndoStackDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StackDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StackDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StackDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/diagrams/UndoRedoStartingStackDiagram.pptx
Labels: priority.high, type.Documentation

#104 Feature Description in UG/DG : email
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/EmailCommandUML.pptx
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/SDforEmail.pptx
  docs/diagrams/SDforEmailCommandParser.pptx
  docs/images/EmailCommandUML.png
  docs/images/SDforEmail.png
  docs/images/SDforEmailCommandParser.png
Labels: status.readyToMerge, type.Documentation

#100 Email Feature
  src/main/java/seedu/club/commons/events/ui/SendEmailRequestEvent.java
  src/main/java/seedu/club/logic/commands/EmailCommand.java
  src/main/java/seedu/club/logic/commands/RemoveGroupCommand.java
  src/main/java/seedu/club/logic/commands/email/Body.java
  src/main/java/seedu/club/logic/commands/email/Client.java
  src/main/java/seedu/club/logic/commands/email/Subject.java
  src/main/java/seedu/club/logic/parser/CliSyntax.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/EmailCommandParser.java
  src/main/java/seedu/club/logic/parser/ParserUtil.java
  src/main/java/seedu/club/logic/parser/RemoveGroupCommandParser.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/group/Group.java
  src/main/java/seedu/club/ui/BrowserPanel.java
  src/test/java/seedu/club/commons/events/ui/SendEmailRequestEventTest.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/CommandTestUtil.java
  src/test/java/seedu/club/logic/commands/EmailCommandTest.java
  src/test/java/seedu/club/logic/commands/RemoveGroupCommandTest.java
  src/test/java/seedu/club/logic/commands/email/BodyTest.java
  src/test/java/seedu/club/logic/commands/email/ClientTest.java
  src/test/java/seedu/club/logic/commands/email/SubjectTest.java
  src/test/java/seedu/club/logic/parser/ClubBookParserTest.java
  src/test/java/seedu/club/logic/parser/EmailCommandParserTest.java
  src/test/java/seedu/club/logic/parser/ParserUtilTest.java
  src/test/java/seedu/club/logic/parser/RemoveGroupCommandParserTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
Labels: enhancement, status.readyForReview, type.Code

#105 Combine Find and Findby Commands
  clubbook.xml
  src/main/java/seedu/club/logic/commands/FindByCommand.java
  src/main/java/seedu/club/logic/commands/FindCommand.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/FindByCommandParser.java
  src/main/java/seedu/club/logic/parser/FindCommandParser.java
  src/main/java/seedu/club/model/member/FieldContainsKeywordsPredicate.java
  src/test/java/seedu/club/logic/commands/FindByCommandTest.java
  src/test/java/seedu/club/logic/commands/FindCommandTest.java
  src/test/java/seedu/club/logic/parser/ClubBookParserTest.java
  src/test/java/seedu/club/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/club/model/member/FieldContainsKeywordsPredicateTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: enhancement, type.Code

#106 [W9.10][W15-B4] Profile Photo
  .gitignore
  clubbook.xml
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ChangeProfilePhotoCommandSdForLogic.pptx
  docs/diagrams/ChangeProfilePhotoCommandUML.pptx
  docs/diagrams/SDforChangeProfilePhoto.pptx
  docs/images/ChangeProfilePhotoCommandSdForLogic.png
  docs/images/ChangeProfilePhotoCommandUML.png
  docs/images/SDforChangeProfilePhoto.png
  src/main/java/seedu/club/MainApp.java
  src/main/java/seedu/club/commons/core/Messages.java
  src/main/java/seedu/club/commons/events/model/ProfilePhotoChangedEvent.java
  src/main/java/seedu/club/commons/exceptions/PhotoException.java
  src/main/java/seedu/club/logic/commands/AddCommand.java
  src/main/java/seedu/club/logic/commands/ChangeProfilePhotoCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/parser/AddCommandParser.java
  src/main/java/seedu/club/logic/parser/ChangeProfilePhotoCommandParser.java
  src/main/java/seedu/club/logic/parser/CliSyntax.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/EditCommandParser.java
  src/main/java/seedu/club/logic/parser/ParserUtil.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/member/Member.java
  src/main/java/seedu/club/model/member/Password.java
  src/main/java/seedu/club/model/member/ProfilePhoto.java
  src/main/java/seedu/club/model/member/Username.java
  src/main/java/seedu/club/storage/PhotoStorage.java
  src/main/java/seedu/club/storage/ProfilePhotoStorage.java
  src/main/java/seedu/club/storage/Storage.java
  src/main/java/seedu/club/storage/StorageManager.java
  src/main/java/seedu/club/storage/XmlAdaptedMember.java
  src/main/java/seedu/club/ui/MemberCard.java
  src/main/resources/images/defaultProfilePhoto.png
  src/main/resources/photos/default.png
  src/main/resources/view/MemberListCard.fxml
  src/test/data/XmlUtilTest/invalidMemberField.xml
  src/test/data/XmlUtilTest/missingMemberField.xml
  src/test/data/XmlUtilTest/validClubBook.xml
  src/test/data/XmlUtilTest/validMember.xml
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/storage/StorageManagerTest.java
  src/test/resources/photos/default.png
Labels: enhancement, status.ToBeRefined, status.readyForReview, type.Code, type.Documentation

#108 Add implementation details in developer guide
  docs/DeveloperGuide.adoc
  docs/images/CompressedCards.png
  docs/images/DecompressedMemberCards.png
  docs/images/MemberCardClassDiagram.png
  docs/images/SDforCompressFromEventsCenter.png
  docs/images/SDforCompressToEventsCenter.png
Labels: priority.high, status.readyForReview, type.Documentation

#117 Update features in UG
  docs/UserGuide.adoc
Labels: status.done, status.readyToMerge, type.Documentation

#116 Randomize tag colors and change group color
  src/main/java/seedu/club/ui/MemberCard.java
  src/main/resources/view/DarkTheme.css
Labels: type.UI

#120 Auto-complete feature
  src/main/java/seedu/club/logic/LogicManager.java
  src/main/java/seedu/club/logic/commands/AddCommand.java
  src/main/java/seedu/club/logic/commands/ChangeProfilePhotoCommand.java
  src/main/java/seedu/club/logic/commands/DeleteCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/commands/EmailCommand.java
  src/main/java/seedu/club/logic/commands/FindCommand.java
  src/main/java/seedu/club/logic/commands/LogInCommand.java
  src/main/java/seedu/club/logic/commands/RemoveGroupCommand.java
  src/main/java/seedu/club/logic/parser/CommandList.java
  src/main/java/seedu/club/ui/CommandBox.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/club/ui/CommandBoxTest.java
Labels: enhancement, status.readyToMerge

#123 Add basic poll related classes and GUI
  clubbook.xml
  src/main/java/seedu/club/commons/events/ui/JumpToPollListRequestEvent.java
  src/main/java/seedu/club/commons/events/ui/PollPanelSelectionChangedEvent.java
  src/main/java/seedu/club/logic/Logic.java
  src/main/java/seedu/club/logic/LogicManager.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/ReadOnlyClubBook.java
  src/main/java/seedu/club/model/poll/Answer.java
  src/main/java/seedu/club/model/poll/Poll.java
  src/main/java/seedu/club/model/poll/Question.java
  src/main/java/seedu/club/model/poll/UniquePollList.java
  src/main/java/seedu/club/model/poll/exceptions/DuplicatePollException.java
  src/main/java/seedu/club/model/util/SampleDataUtil.java
  src/main/java/seedu/club/storage/XmlAdaptedAnswer.java
  src/main/java/seedu/club/storage/XmlAdaptedMatricNumber.java
  src/main/java/seedu/club/storage/XmlAdaptedPoll.java
  src/main/java/seedu/club/storage/XmlSerializableClubBook.java
  src/main/java/seedu/club/ui/MainWindow.java
  src/main/java/seedu/club/ui/PollCard.java
  src/main/java/seedu/club/ui/PollListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PollListCard.fxml
  src/main/resources/view/PollListPanel.fxml
  src/test/data/XmlSerializableClubBookTest/invalidPollClubBook.xml
  src/test/data/XmlSerializableClubBookTest/typicalPollsClubBook.xml
  src/test/java/seedu/club/logic/LogicManagerTest.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/CommandTestUtil.java
  src/test/java/seedu/club/model/ClubBookTest.java
  src/test/java/seedu/club/model/poll/AnswerTest.java
  src/test/java/seedu/club/model/poll/PollTest.java
  src/test/java/seedu/club/model/poll/QuestionTest.java
  src/test/java/seedu/club/model/poll/UniquePollListTest.java
  src/test/java/seedu/club/storage/XmlAdaptedAnswerTest.java
  src/test/java/seedu/club/storage/XmlAdaptedMatricNumberTest.java
  src/test/java/seedu/club/storage/XmlAdaptedPollTest.java
  src/test/java/seedu/club/storage/XmlSerializableClubBookTest.java
  src/test/java/seedu/club/testutil/PollBuilder.java
  src/test/java/seedu/club/testutil/TypicalPolls.java
Labels: enhancement, priority.high, status.readyToMerge, type.Code, type.task

#127 Add photos to compressed view
  src/main/java/seedu/club/MainApp.java
  src/main/java/seedu/club/logic/commands/AddCommand.java
  src/main/java/seedu/club/logic/commands/ChangeProfilePhotoCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/parser/AddCommandParser.java
  src/main/java/seedu/club/logic/parser/CliSyntax.java
  src/main/java/seedu/club/logic/parser/EditCommandParser.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/UserPrefs.java
  src/main/java/seedu/club/model/member/Member.java
  src/main/java/seedu/club/storage/XmlAdaptedMember.java
  src/main/java/seedu/club/ui/CompressedMemberCard.java
  src/main/java/seedu/club/ui/MemberCard.java
  src/main/java/seedu/club/ui/MemberListPanel.java
  src/main/resources/images/defaultProfilePhoto.png
  src/main/resources/view/CompressedMemberListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MemberListCard.fxml
Labels: enhancement, priority.high, status.readyForReview

#128 UI Revamp
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MemberListCard.fxml
  src/main/resources/view/TaskCompleted.css
  src/main/resources/view/TaskInProgress.css
  src/main/resources/view/TaskYetToBegin.css
Labels: status.readyToMerge, type.UI

#109 Improve logIn features
  clubbook.xml
  src/main/java/seedu/club/logic/commands/AddCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/commands/LogInCommand.java
  src/main/java/seedu/club/logic/parser/AddCommandParser.java
  src/main/java/seedu/club/logic/parser/CliSyntax.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/ReadOnlyClubBook.java
  src/main/java/seedu/club/model/member/Credentials.java
  src/main/java/seedu/club/model/member/Member.java
  src/main/java/seedu/club/model/member/UniqueMemberList.java
  src/main/java/seedu/club/model/util/SampleDataUtil.java
  src/main/java/seedu/club/storage/XmlAdaptedMember.java
  src/test/java/seedu/club/commons/util/XmlUtilTest.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/club/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/club/logic/commands/EditCommandTest.java
  src/test/java/seedu/club/logic/commands/EmailCommandTest.java
  src/test/java/seedu/club/logic/commands/ListCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/RedoCommandTest.java
  src/test/java/seedu/club/logic/commands/RemoveGroupCommandTest.java
  src/test/java/seedu/club/logic/commands/SelectCommandTest.java
  src/test/java/seedu/club/logic/commands/UndoCommandTest.java
  src/test/java/seedu/club/logic/commands/UndoableCommandTest.java
  src/test/java/seedu/club/model/ClubBookTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/seedu/club/storage/XmlAdaptedMemberTest.java
  src/test/java/seedu/club/testutil/MemberBuilder.java
  src/test/java/seedu/club/testutil/MemberUtil.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddTaskCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/DeleteTagCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/RemoveGroupCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.high, status.done, status.readyToMerge, type.Code

#126 [W10.8][W15-B4]Export
  .gitignore
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/club/MainApp.java
  src/main/java/seedu/club/commons/events/model/NewExportDataAvailableEvent.java
  src/main/java/seedu/club/commons/events/model/ProfilePhotoChangedEvent.java
  src/main/java/seedu/club/commons/util/CsvUtil.java
  src/main/java/seedu/club/commons/util/FileUtil.java
  src/main/java/seedu/club/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/commands/ExportCommand.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/ExportCommandParser.java
  src/main/java/seedu/club/logic/parser/ParserUtil.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/member/Member.java
  src/main/java/seedu/club/model/tag/Tag.java
  src/main/java/seedu/club/storage/CsvClubBookStorage.java
  src/main/java/seedu/club/storage/CsvFileStorage.java
  src/main/java/seedu/club/storage/ProfilePhotoStorage.java
  src/main/java/seedu/club/storage/Storage.java
  src/main/java/seedu/club/storage/StorageManager.java
  src/main/java/seedu/club/ui/MemberCard.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/storage/StorageManagerTest.java
Labels: enhancement, needsDocumentation, priority.high, status.ToBeRefined, status.readyForReview, type.Code

#131 [W10.8][W15-B4] Implementation of logout feature
  docs/UserGuide.adoc
  src/main/java/seedu/club/logic/commands/LogOutCommand.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/member/Member.java
  src/main/java/seedu/club/model/member/UniqueMemberList.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/LogOutCommandTest.java
Labels: priority.medium, status.done, status.readyToMerge

#132 Fixes
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/ui/MemberCard.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/systemtests/AddTaskCommandSystemTest.java
Labels: status.readyToMerge

#133 Fix photos for JAR file
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/member/Member.java
  src/main/java/seedu/club/model/member/ProfilePhoto.java
  src/main/java/seedu/club/storage/ProfilePhotoStorage.java
  src/main/java/seedu/club/storage/XmlAdaptedMember.java
  src/main/java/seedu/club/ui/MemberCard.java
Labels: priority.high, status.readyToMerge

#143 Update auto-complete commands
  src/main/java/seedu/club/logic/commands/AddPollCommand.java
  src/main/java/seedu/club/logic/commands/ExportCommand.java
  src/main/java/seedu/club/logic/commands/SelectCommand.java
  src/main/java/seedu/club/logic/parser/CommandList.java
Labels: status.readyForReview

#141 Fixes - Task viewing + Tests
  src/main/java/seedu/club/logic/commands/AddTaskCommand.java
  src/main/java/seedu/club/logic/commands/EmailCommand.java
  src/main/java/seedu/club/logic/commands/RemoveGroupCommand.java
  src/main/java/seedu/club/logic/parser/CommandList.java
  src/main/java/seedu/club/logic/parser/EmailCommandParser.java
  src/main/java/seedu/club/logic/parser/RemoveGroupCommandParser.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/email/Body.java
  src/main/java/seedu/club/model/email/Client.java
  src/main/java/seedu/club/model/email/Subject.java
  src/main/java/seedu/club/model/group/Group.java
  src/main/java/seedu/club/model/group/exceptions/GroupCannotBeRemovedException.java
  src/main/java/seedu/club/model/group/exceptions/GroupNotFoundException.java
  src/main/java/seedu/club/model/task/Assignor.java
  src/main/java/seedu/club/model/task/Date.java
  src/main/java/seedu/club/model/task/Status.java
  src/main/java/seedu/club/model/task/Task.java
  src/main/java/seedu/club/model/task/TaskIsRelatedToMemberPredicate.java
  src/main/java/seedu/club/storage/XmlAdaptedTask.java
  src/main/java/seedu/club/ui/TaskListPanel.java
  src/main/resources/view/TaskCompleted.css
  src/main/resources/view/TaskInProgress.css
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/java/seedu/club/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/club/testutil/TestUtil.java
  src/test/java/systemtests/DeleteTaskCommandSystemTest.java
Labels: status.readyForReview, type.fix

#142 ViewAllTasksCommand
  src/main/java/seedu/club/logic/commands/ViewAllTasksCommand.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/CommandList.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/group/Group.java
  src/main/java/seedu/club/model/task/exceptions/TasksCannotBeDisplayedException.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/CommandTestUtil.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/ViewAllTasksCommandTest.java
  src/test/java/seedu/club/logic/parser/ClubBookParserTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/seedu/club/testutil/TypicalMembers.java
  src/test/java/systemtests/RemoveGroupCommandSystemTest.java
Labels: priority.medium, status.readyForReview, type.task
