Repository CS2103JAN2018-W15-B4/main, pull requests merged in 2018-04, with the labels that each got.

#147 ViewMyTasks Command
  src/main/java/seedu/club/logic/commands/ViewMyTasksCommand.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/CommandList.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/task/TaskIsRelatedToMemberPredicate.java
  src/main/java/seedu/club/model/task/exceptions/TasksAlreadyListedException.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/ExportCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/club/logic/commands/ViewMyTasksCommandTest.java
  src/test/java/seedu/club/logic/parser/ClubBookParserTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/seedu/club/testutil/TypicalTasks.java
Labels: priority.medium, status.readyForReview

#155 Import command
  docs/images/Ui.png
  src/main/java/seedu/club/commons/core/Messages.java
  src/main/java/seedu/club/commons/events/model/ProfilePhotoChangedEvent.java
  src/main/java/seedu/club/commons/exceptions/DataConversionException.java
  src/main/java/seedu/club/commons/util/CsvUtil.java
  src/main/java/seedu/club/logic/LogicManager.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/commands/ExportCommand.java
  src/main/java/seedu/club/logic/commands/ImportCommand.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/ImportCommandParser.java
  src/main/java/seedu/club/logic/parser/ParserUtil.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/member/Member.java
  src/main/java/seedu/club/model/member/ProfilePhoto.java
  src/main/java/seedu/club/storage/CsvClubBookStorage.java
  src/main/java/seedu/club/storage/CsvFileStorage.java
  src/main/java/seedu/club/storage/ProfilePhotoStorage.java
  src/main/java/seedu/club/storage/StorageManager.java
  src/main/java/seedu/club/ui/CommandBox.java
  src/main/java/seedu/club/ui/MemberCard.java
  src/main/resources/view/MemberListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/ExportCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/seedu/club/testutil/ClubBookBuilder.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: enhancement, priority.high, status.Ongoing, type.Code

#152 Implement Changepassword function
  docs/UserGuide.adoc
  src/main/java/seedu/club/logic/commands/ChangePasswordCommand.java
  src/main/java/seedu/club/logic/commands/SignUpCommand.java
  src/main/java/seedu/club/logic/parser/ChangePasswordCommandParser.java
  src/main/java/seedu/club/logic/parser/CliSyntax.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/ParserUtil.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/member/Credentials.java
  src/main/java/seedu/club/model/member/UniqueMemberList.java
  src/main/java/seedu/club/model/member/exceptions/DataToChangeIsNotCurrentlyLoggedInMemberException.java
  src/main/java/seedu/club/model/member/exceptions/PasswordIncorrectException.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangePasswordCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/ExportCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/systemtests/ChangePasswordCommandSystemTest.java
Labels: priority.medium, status.readyToMerge

#159 Command Aliases
  docs/UserGuide.adoc
  src/main/java/seedu/club/logic/commands/AddCommand.java
  src/main/java/seedu/club/logic/commands/AddPollCommand.java
  src/main/java/seedu/club/logic/commands/AddTaskCommand.java
  src/main/java/seedu/club/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/club/logic/commands/ChangePasswordCommand.java
  src/main/java/seedu/club/logic/commands/ChangeProfilePhotoCommand.java
  src/main/java/seedu/club/logic/commands/ClearCommand.java
  src/main/java/seedu/club/logic/commands/CompressCommand.java
  src/main/java/seedu/club/logic/commands/DecompressCommand.java
  src/main/java/seedu/club/logic/commands/DeleteCommand.java
  src/main/java/seedu/club/logic/commands/DeletePollCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/commands/EmailCommand.java
  src/main/java/seedu/club/logic/commands/ExitCommand.java
  src/main/java/seedu/club/logic/commands/ExportCommand.java
  src/main/java/seedu/club/logic/commands/FindCommand.java
  src/main/java/seedu/club/logic/commands/HelpCommand.java
  src/main/java/seedu/club/logic/commands/HideResultsCommand.java
  src/main/java/seedu/club/logic/commands/HistoryCommand.java
  src/main/java/seedu/club/logic/commands/ImportCommand.java
  src/main/java/seedu/club/logic/commands/ListCommand.java
  src/main/java/seedu/club/logic/commands/LogInCommand.java
  src/main/java/seedu/club/logic/commands/LogOutCommand.java
  src/main/java/seedu/club/logic/commands/RedoCommand.java
  src/main/java/seedu/club/logic/commands/RemoveGroupCommand.java
  src/main/java/seedu/club/logic/commands/SelectCommand.java
  src/main/java/seedu/club/logic/commands/ShowResultsCommand.java
  src/main/java/seedu/club/logic/commands/SignUpCommand.java
  src/main/java/seedu/club/logic/commands/UndoCommand.java
  src/main/java/seedu/club/logic/commands/ViewAllTasksCommand.java
  src/main/java/seedu/club/logic/commands/ViewMyTasksCommand.java
  src/main/java/seedu/club/logic/commands/VoteCommand.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/test/java/guitests/GuiRobot.java
Labels: priority.low, status.readyToMerge

#151 Update User Guide
  docs/UserGuide.adoc
Labels: type.Documentation

#164 Clean Up
  docs/UserGuide.adoc
  src/main/java/seedu/club/commons/util/CsvUtil.java
  src/main/java/seedu/club/commons/util/FileUtil.java
  src/main/java/seedu/club/logic/commands/AddCommand.java
  src/main/java/seedu/club/logic/commands/AddPollCommand.java
  src/main/java/seedu/club/logic/commands/AddTaskCommand.java
  src/main/java/seedu/club/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/club/logic/commands/ChangePasswordCommand.java
  src/main/java/seedu/club/logic/commands/ChangeProfilePhotoCommand.java
  src/main/java/seedu/club/logic/commands/ClearCommand.java
  src/main/java/seedu/club/logic/commands/CompressCommand.java
  src/main/java/seedu/club/logic/commands/DecompressCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/commands/EmailCommand.java
  src/main/java/seedu/club/logic/commands/ExportCommand.java
  src/main/java/seedu/club/logic/commands/FindCommand.java
  src/main/java/seedu/club/logic/commands/HelpCommand.java
  src/main/java/seedu/club/logic/commands/HideResultsCommand.java
  src/main/java/seedu/club/logic/commands/ImportCommand.java
  src/main/java/seedu/club/logic/commands/ListCommand.java
  src/main/java/seedu/club/logic/commands/LogInCommand.java
  src/main/java/seedu/club/logic/commands/LogOutCommand.java
  src/main/java/seedu/club/logic/commands/RedoCommand.java
  src/main/java/seedu/club/logic/commands/RemoveGroupCommand.java
  src/main/java/seedu/club/logic/commands/SelectCommand.java
  src/main/java/seedu/club/logic/commands/ShowResultsCommand.java
  src/main/java/seedu/club/logic/commands/SignUpCommand.java
  src/main/java/seedu/club/logic/commands/UndoCommand.java
  src/main/java/seedu/club/logic/commands/ViewAllTasksCommand.java
  src/main/java/seedu/club/logic/commands/ViewMyTasksCommand.java
  src/main/java/seedu/club/logic/commands/VoteCommand.java
  src/main/java/seedu/club/logic/parser/ParserUtil.java
  src/main/java/seedu/club/model/group/Group.java
  src/main/java/seedu/club/model/member/ProfilePhoto.java
  src/main/java/seedu/club/storage/CsvClubBookStorage.java
  src/main/java/seedu/club/storage/XmlAdaptedMember.java
  src/main/java/seedu/club/ui/MemberCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PollListCard.fxml
  src/main/resources/view/RestrictedAnswerListCard.fxml
  src/main/resources/view/RestrictedPollListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/CommandTestUtil.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/RemoveGroupCommandTest.java
  src/test/java/systemtests/RemoveGroupCommandSystemTest.java
Labels: status.readyForReview

#166 ChangeTaskStatus Command
  build.gradle
  collated/functional/Song.md
  collated/functional/yash-chowdhary.md
  collated/test/amrut-prabhu.md
  collated/test/yash-chowdhary.md
  docs/UserGuide.adoc
  docs/images/Ui.png
  src/main/java/seedu/club/commons/core/Messages.java
  src/main/java/seedu/club/logic/commands/ChangeTaskStatusCommand.java
  src/main/java/seedu/club/logic/commands/DeleteCommand.java
  src/main/java/seedu/club/logic/commands/DeletePollCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/commands/EmailCommand.java
  src/main/java/seedu/club/logic/commands/RemoveGroupCommand.java
  src/main/java/seedu/club/logic/commands/SignUpCommand.java
  src/main/java/seedu/club/logic/commands/VoteCommand.java
  src/main/java/seedu/club/logic/parser/ChangeTaskStatusCommandParser.java
  src/main/java/seedu/club/logic/parser/CliSyntax.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/CommandList.java
  src/main/java/seedu/club/logic/parser/ParserUtil.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/task/Status.java
  src/main/java/seedu/club/model/task/Task.java
  src/main/java/seedu/club/model/task/UniqueTaskList.java
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeTaskStatusCommandTest.java
  src/test/java/seedu/club/logic/commands/DeletePollCommandTest.java
  src/test/java/seedu/club/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/EmailCommandTest.java
  src/test/java/seedu/club/logic/commands/ExportCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/RemoveGroupCommandTest.java
  src/test/java/seedu/club/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/club/logic/parser/ChangeTaskStatusCommandParserTest.java
  src/test/java/seedu/club/model/ClubBookTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/systemtests/AddTaskCommandSystemTest.java
  src/test/java/systemtests/AssignTaskCommandSystemTest.java
  src/test/java/systemtests/DeleteTaskCommandSystemTest.java
  src/test/java/systemtests/EmailCommandSystemTest.java
  src/test/java/systemtests/RemoveGroupCommandSystemTest.java
Labels: enhancement, priority.high, status.readyForReview, type.task

#172 UG updates
  .gitignore
  collated/functional/MuhdNurKamal.md
  collated/functional/Song.md
  collated/functional/amrut-prabhu.md
  collated/functional/yash-chowdhary.md
  collated/test/amrut-prabhu.md
  collated/test/yash-chowdhary.md
  docs/UserGuide.adoc
  docs/images/CSV_format.png
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/member/Member.java
  src/main/java/seedu/club/model/member/Name.java
Labels: type.Documentation

#168 Revamp implementation of Clear Command
  docs/UserGuide.adoc
  src/main/java/seedu/club/logic/commands/ClearCommand.java
  src/main/java/seedu/club/logic/parser/ClearCommandParser.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/member/UniqueMemberList.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/ClearCommandTest.java
  src/test/java/seedu/club/logic/commands/ExportCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/SignUpCommandTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/ClubBookSystemTest.java
Labels: enhancement, status.readyToMerge

#173 Add requireExcoLogIn
  src/main/java/seedu/club/commons/core/Messages.java
  src/main/java/seedu/club/logic/commands/AddCommand.java
  src/main/java/seedu/club/logic/commands/AddPollCommand.java
  src/main/java/seedu/club/logic/commands/AddTaskCommand.java
  src/main/java/seedu/club/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/club/logic/commands/ChangePasswordCommand.java
  src/main/java/seedu/club/logic/commands/ChangeProfilePhotoCommand.java
  src/main/java/seedu/club/logic/commands/ChangeTaskStatusCommand.java
  src/main/java/seedu/club/logic/commands/ClearCommand.java
  src/main/java/seedu/club/logic/commands/Command.java
  src/main/java/seedu/club/logic/commands/DeleteCommand.java
  src/main/java/seedu/club/logic/commands/DeletePollCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/commands/EmailCommand.java
  src/main/java/seedu/club/logic/commands/ExportCommand.java
  src/main/java/seedu/club/logic/commands/ImportCommand.java
  src/main/java/seedu/club/logic/commands/RemoveGroupCommand.java
  src/main/java/seedu/club/logic/commands/ShowResultsCommand.java
  src/main/java/seedu/club/logic/commands/ViewAllTasksCommand.java
  src/main/java/seedu/club/logic/commands/ViewMyTasksCommand.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/ExportCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/systemtests/AssignTaskCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.high, status.readyForReview

#174 Solve undo bug
  src/main/java/seedu/club/commons/core/Messages.java
  src/main/java/seedu/club/logic/LogicManager.java
  src/main/java/seedu/club/logic/UndoRedoStack.java
  src/main/java/seedu/club/logic/commands/ChangeTaskStatusCommand.java
  src/main/java/seedu/club/logic/commands/Command.java
  src/main/java/seedu/club/logic/commands/LogInCommand.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
Labels: priority.high, status.readyForReview

#175 Matric Number - Task Assignors and Assignees
  docs/UserGuide.adoc
  src/main/java/seedu/club/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/club/logic/parser/AssignTaskCommandParser.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/member/MatricNumber.java
  src/main/java/seedu/club/model/task/TaskIsRelatedToMemberPredicate.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeTaskStatusCommandTest.java
  src/test/java/seedu/club/logic/commands/CommandTestUtil.java
  src/test/java/seedu/club/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ExportCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/club/logic/parser/AssignTaskCommandParserTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/seedu/club/testutil/TypicalTasks.java
  src/test/java/systemtests/AssignTaskCommandSystemTest.java
Labels: status.readyToMerge

#171 Improve Polls GUI
  docs/UserGuide.adoc
  src/main/java/seedu/club/commons/events/ui/HideResultsRequestEvent.java
  src/main/java/seedu/club/commons/events/ui/PollPanelSelectionChangedEvent.java
  src/main/java/seedu/club/commons/events/ui/ShowResultsRequestEvent.java
  src/main/java/seedu/club/logic/commands/AddPollCommand.java
  src/main/java/seedu/club/logic/commands/CompressCommand.java
  src/main/java/seedu/club/logic/commands/DecompressCommand.java
  src/main/java/seedu/club/logic/commands/DeletePollCommand.java
  src/main/java/seedu/club/logic/commands/HideResultsCommand.java
  src/main/java/seedu/club/logic/parser/AddPollCommandParser.java
  src/main/java/seedu/club/logic/parser/DeletePollCommandParser.java
  src/main/java/seedu/club/logic/parser/FindCommandParser.java
  src/main/java/seedu/club/logic/parser/ParserUtil.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/poll/exceptions/AnswerNotFoundException.java
  src/main/java/seedu/club/model/poll/exceptions/UserAlreadyVotedException.java
  src/main/java/seedu/club/ui/AnswerCard.java
  src/main/java/seedu/club/ui/AnswerListPanel.java
  src/main/java/seedu/club/ui/PollCard.java
  src/main/java/seedu/club/ui/PollListPanel.java
  src/main/java/seedu/club/ui/RestrictedPollCard.java
  src/main/resources/view/AnswerListCard.fxml
  src/main/resources/view/AnswerListPanel.fxml
  src/main/resources/view/RestrictedAnswerListCard.fxml
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/CompressCommandTest.java
  src/test/java/seedu/club/logic/commands/DeletePollCommandTest.java
  src/test/java/seedu/club/logic/commands/ShowResultsCommandTest.java
  src/test/java/seedu/club/logic/parser/AddPollCommandParserTest.java
  src/test/java/seedu/club/testutil/PollBuilder.java
  src/test/java/seedu/club/testutil/PollUtil.java
  src/test/java/seedu/club/testutil/TypicalPolls.java
  src/test/java/systemtests/AddPollCommandSystemTest.java
Labels: status.readyForReview, type.Code, type.UI

#176 Code cleanup
  src/main/java/seedu/club/logic/commands/Command.java
  src/main/java/seedu/club/logic/commands/ViewAllTasksCommand.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/tag/Tag.java
  src/test/java/seedu/club/logic/commands/ViewAllTasksCommandTest.java
Labels: code.cleanup

#209 Enhancements - Delete+Edit member + UG fixes
  docs/UserGuide.adoc
  src/main/java/seedu/club/logic/commands/Command.java
  src/main/java/seedu/club/logic/commands/DeleteCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/parser/CommandList.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/ReadOnlyClubBook.java
  src/main/java/seedu/club/model/member/Member.java
  src/main/java/seedu/club/model/task/UniqueTaskList.java
  src/main/java/seedu/club/ui/CommandBox.java
  src/test/data/XmlSerializableClubBookTest/typicalMembersClubBook.xml
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/CommandTestUtil.java
  src/test/java/seedu/club/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/club/logic/commands/EditCommandTest.java
  src/test/java/seedu/club/logic/commands/ExportCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/RemoveGroupCommandTest.java
  src/test/java/seedu/club/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/club/model/ClubBookTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/seedu/club/model/group/GroupTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.Code, type.Documentation

#208 Minor fixes
  collated/test/th14thmusician.md
  src/main/java/seedu/club/logic/commands/ClearCommand.java
  src/main/java/seedu/club/logic/commands/ImportCommand.java
  src/main/java/seedu/club/logic/parser/ImportCommandParser.java
  src/main/java/seedu/club/logic/parser/ParserUtil.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/UserPrefs.java
  src/main/java/seedu/club/model/group/Group.java
  src/main/java/seedu/club/model/member/Member.java
  src/main/java/seedu/club/model/tag/Tag.java
  src/main/java/seedu/club/model/util/SampleDataUtil.java
  src/main/resources/view/MemberListCard.fxml
  src/test/data/XmlSerializableClubBookTest/invalidPollClubBook.xml
  src/test/data/XmlSerializableClubBookTest/invalidTagClubBook.xml
  src/test/data/XmlSerializableClubBookTest/invalidTaskClubBook.xml
  src/test/data/XmlSerializableClubBookTest/typicalMembersClubBook.xml
  src/test/data/XmlSerializableClubBookTest/typicalPollsClubBook.xml
  src/test/data/XmlSerializableClubBookTest/typicalTasksClubBook.xml
  src/test/data/XmlUtilTest/invalidMemberField.xml
  src/test/data/XmlUtilTest/missingMemberField.xml
  src/test/data/XmlUtilTest/tempClubBook.xml
  src/test/data/XmlUtilTest/validMember.xml
  src/test/java/seedu/club/commons/util/XmlUtilTest.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/CommandTestUtil.java
  src/test/java/seedu/club/logic/commands/ExportCommandTest.java
  src/test/java/seedu/club/logic/commands/FindCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/club/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/club/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/club/logic/parser/EmailCommandParserTest.java
  src/test/java/seedu/club/model/ClubBookTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/seedu/club/model/UniqueTagListTest.java
  src/test/java/seedu/club/model/group/GroupTest.java
  src/test/java/seedu/club/testutil/MemberBuilder.java
  src/test/java/seedu/club/testutil/TypicalMembers.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/DeleteTagCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/EmailCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/RemoveGroupCommandSystemTest.java
  src/test/java/systemtests/SignUpCommandSystemTest.java
Labels: status.readyForReview, type.fix

#215 ChangeAssignee Command
  docs/UserGuide.adoc
  src/main/java/seedu/club/commons/events/ui/SendEmailRequestEvent.java
  src/main/java/seedu/club/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/club/logic/commands/ChangeAssigneeCommand.java
  src/main/java/seedu/club/logic/commands/ChangeTaskStatusCommand.java
  src/main/java/seedu/club/logic/commands/ViewAllTasksCommand.java
  src/main/java/seedu/club/logic/parser/ChangeAssigneeCommandParser.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/CommandList.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/task/UniqueTaskList.java
  src/main/java/seedu/club/model/task/exceptions/TaskAlreadyAssignedException.java
  src/main/java/seedu/club/model/task/exceptions/TaskAssigneeUnchangedException.java
  src/main/java/seedu/club/model/task/exceptions/TaskStatusCannotBeEditedException.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeAssigneeCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeTaskStatusCommandTest.java
  src/test/java/seedu/club/logic/commands/ExportCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/club/logic/parser/ChangeAssigneeCommandParserTest.java
  src/test/java/seedu/club/model/ClubBookTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
Labels: enhancement, priority.medium, type.task

#187 Fix polls
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/commands/LogOutCommand.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/poll/PollIsRelevantToMemberPredicate.java
  src/test/java/seedu/club/logic/commands/LogOutCommandTest.java
Labels: status.readyToMerge, type.fix

#210 Fix FindCommandParser
  src/main/java/seedu/club/logic/parser/FindCommandParser.java
  src/test/java/seedu/club/logic/commands/FindCommandTest.java
  src/test/java/seedu/club/logic/parser/FindCommandParserTest.java
Labels: status.readyToMerge, type.fix

#218 Add titles for panes(columns)
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MemberListPanel.fxml
  src/main/resources/view/PollListPanel.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: priority.low, status.readyToMerge, type.UI

#211 Solve Bug that does not display incorrect username while changing password
  src/main/java/seedu/club/logic/commands/ChangePasswordCommand.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/member/UniqueMemberList.java
  src/main/java/seedu/club/model/member/exceptions/MatricNumberNotFoundException.java
  src/test/java/seedu/club/logic/commands/ChangePasswordCommandTest.java
Labels: bug, status.readyForReview

#220 Add Portfolio
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/RemoveGroupCommandUML.pptx
  docs/diagrams/SDforAddTask.pptx
  docs/diagrams/SDforAddTaskCommandParser.pptx
  docs/diagrams/SDforAssignTask.pptx
  docs/diagrams/SDforAssignTaskCommandParser.pptx
  docs/diagrams/SDforChangeTaskStatus.pptx
  docs/diagrams/SDforChangeTaskStatusCommandParser.pptx
  docs/diagrams/SDforDeleteTask.pptx
  docs/diagrams/SDforDeleteTaskCommandParser.pptx
  docs/diagrams/SDforRemoveGroup.pptx
  docs/diagrams/SDforRemoveGroupCommandParser.pptx
  docs/diagrams/SDforViewAllTasks.pptx
  docs/diagrams/SDforViewMyTasks.pptx
  docs/diagrams/TaskUML.pptx
  docs/images/LogicClassDiagram/Slide1.PNG
  docs/images/LogicCommandClassDiagram/Slide1.PNG
  docs/images/RemoveGroupCommandUML.png
  docs/images/SDforAddTask.png
  docs/images/SDforAddTaskCommandParser.png
  docs/images/SDforAssignTask.png
  docs/images/SDforAssignTaskCommandParser.png
  docs/images/SDforChangeTaskStatus.png
  docs/images/SDforChangeTaskStatusCommandParser.png
  docs/images/SDforDeleteTask.png
  docs/images/SDforDeleteTaskCommandParser.png
  docs/images/SDforRemoveGroup.png
  docs/images/SDforRemoveGroupCommandParser.png
  docs/images/SDforViewAllTasks.png
  docs/images/SDforViewMyTasks.png
  docs/images/TaskUML.png
  docs/images/login.png
  docs/images/startup.png
  docs/team/yash-chowdhary.adoc
Labels: status.readyToMerge, type.Documentation

#214 Change password is not preserved across sessions
  src/main/java/seedu/club/model/member/Credentials.java
  src/main/java/seedu/club/model/member/UniqueMemberList.java
  src/main/java/seedu/club/storage/XmlAdaptedMember.java
  src/test/data/XmlUtilTest/invalidMemberField.xml
  src/test/data/XmlUtilTest/missingMemberField.xml
  src/test/data/XmlUtilTest/validClubBook.xml
  src/test/data/XmlUtilTest/validMember.xml
  src/test/java/seedu/club/commons/util/XmlUtilTest.java
  src/test/java/seedu/club/logic/commands/ChangePasswordCommandTest.java
  src/test/java/systemtests/AddPollCommandSystemTest.java
Labels: status.readyToMerge

#216 Implement select UI
  src/main/java/seedu/club/commons/events/ui/ClearMemberSelectPanelEvent.java
  src/main/java/seedu/club/commons/events/ui/ModifiedTaskPanelSelecetionChangedEvent.java
  src/main/java/seedu/club/commons/events/ui/UpdateSelectionPanelEvent.java
  src/main/java/seedu/club/logic/Logic.java
  src/main/java/seedu/club/logic/LogicManager.java
  src/main/java/seedu/club/logic/commands/ChangeProfilePhotoCommand.java
  src/main/java/seedu/club/logic/commands/ClearCommand.java
  src/main/java/seedu/club/logic/commands/DeleteCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/commands/LogOutCommand.java
  src/main/java/seedu/club/ui/BrowserPanel.java
  src/main/java/seedu/club/ui/MainWindow.java
  src/main/java/seedu/club/ui/MemberOverviewPanel.java
  src/main/java/seedu/club/ui/ModifiedTaskCard.java
  src/main/java/seedu/club/ui/UiManager.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MemberDetailsPanel.fxml
  src/main/resources/view/ModifiedTaskListCard.fxml
  src/main/resources/view/TaskListCard.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/club/ui/BrowserPanelTest.java
  src/test/java/systemtests/ClubBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/DeleteTaskCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: enhancement, status.readyForReview

#219 Change Theme of app
  docs/UserGuide.adoc
  src/main/java/seedu/club/MainApp.java
  src/main/java/seedu/club/commons/core/Messages.java
  src/main/java/seedu/club/logic/commands/SignUpCommand.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/poll/Question.java
  src/main/java/seedu/club/ui/AnswerCard.java
  src/main/java/seedu/club/ui/MemberCard.java
  src/main/java/seedu/club/ui/MemberOverviewPanel.java
  src/main/java/seedu/club/ui/PollCard.java
  src/main/java/seedu/club/ui/StatusBarFooter.java
  src/main/resources/view/AnswerListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MemberListCard.fxml
  src/main/resources/view/PollListCard.fxml
  src/main/resources/view/RestrictedAnswerListCard.fxml
  src/main/resources/view/RestrictedPollListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TaskYetToBegin.css
  src/test/java/seedu/club/model/poll/QuestionTest.java
  src/test/java/seedu/club/ui/StatusBarFooterTest.java
  src/test/java/systemtests/ClubBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/DeleteTaskCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.medium, status.Ongoing, type.UI

#213 Add tests and improve vote command parsing
  src/main/java/seedu/club/logic/commands/VoteCommand.java
  src/main/java/seedu/club/logic/parser/ParserUtil.java
  src/test/java/seedu/club/logic/commands/CommandTestUtil.java
  src/test/java/seedu/club/logic/commands/DeletePollCommandTest.java
  src/test/java/seedu/club/logic/commands/VoteCommandTest.java
  src/test/java/seedu/club/logic/parser/VoteCommandParserTest.java
  src/test/java/seedu/club/testutil/TestUtil.java
  src/test/java/seedu/club/testutil/TypicalIndexes.java
  src/test/java/seedu/club/testutil/TypicalMembers.java
  src/test/java/seedu/club/testutil/TypicalPolls.java
  src/test/java/systemtests/AddPollCommandSystemTest.java
  src/test/java/systemtests/DeletePollCommandSystemTest.java
Labels: status.readyForReview, type.fix

#226 Improve efficiency of Profile Photo
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  src/main/java/seedu/club/storage/ProfilePhotoStorage.java
  src/test/java/seedu/club/storage/ProfilePhotoStorageTest.java
Labels: status.readyForReview, type.fix

#225 Refactor removegroup
  collated/functional/yash-chowdhary.md
  collated/test/yash-chowdhary.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/RemoveGroupCommandUML.pptx
  docs/diagrams/SDforRemoveGroup.pptx
  docs/diagrams/SDforRemoveGroupCommandParser.pptx
  docs/diagrams/TaskUML.pptx
  docs/images/DeleteGroupCommandUML.png
  docs/images/RemoveGroupCommandUML.png
  docs/images/SDforDeleteGroup.png
  docs/images/SDforDeleteGroupCommandParser.png
  docs/images/SDforRemoveGroup.png
  docs/images/SDforRemoveGroupCommandParser.png
  docs/images/TaskUML.png
  docs/team/yash-chowdhary.adoc
  src/main/java/seedu/club/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/CommandList.java
  src/main/java/seedu/club/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/Model.java
  src/main/java/seedu/club/model/ModelManager.java
  src/test/java/seedu/club/logic/commands/AddCommandTest.java
  src/test/java/seedu/club/logic/commands/AddPollCommandTest.java
  src/test/java/seedu/club/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeProfilePhotoCommandTest.java
  src/test/java/seedu/club/logic/commands/CommandTestUtil.java
  src/test/java/seedu/club/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/club/logic/commands/ExportCommandTest.java
  src/test/java/seedu/club/logic/commands/LogInCommandTest.java
  src/test/java/seedu/club/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/club/logic/parser/ClubBookParserTest.java
  src/test/java/seedu/club/logic/parser/DeleteGroupCommandParserTest.java
  src/test/java/seedu/club/model/ClubBookTest.java
  src/test/java/seedu/club/model/ModelManagerTest.java
  src/test/java/systemtests/DeleteGroupCommandSystemTest.java
Labels: status.readyForReview

#227 Rename showresults to viewresults
  collated/functional/yash-chowdhary.md
  docs/UserGuide.adoc
  docs/team/MuhdNurKamal.adoc
  src/main/java/seedu/club/commons/events/ui/ViewResultsRequestEvent.java
  src/main/java/seedu/club/logic/commands/ViewResultsCommand.java
  src/main/java/seedu/club/logic/parser/ClubBookParser.java
  src/main/java/seedu/club/logic/parser/CommandList.java
  src/main/java/seedu/club/ui/PollListPanel.java
  src/test/java/seedu/club/logic/commands/ViewResultsCommandTest.java
  src/test/java/seedu/club/logic/parser/ClubBookParserTest.java
Labels: status.readyForReview

#228 Cleanup
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddTaskCommandUML.pptx
  docs/diagrams/AssignTaskCommandUML.pptx
  docs/diagrams/ChangeAssigneeCommandUML.pptx
  docs/diagrams/ChangeTaskStatusCommandUML.pptx
  docs/diagrams/DeleteTaskCommandUML.pptx
  docs/diagrams/SDforChangeAssignee.pptx
  docs/diagrams/SDforChangeAssigneeCommandParser.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/AddTaskCommandUML.png
  docs/images/AssignTaskCommandUML.png
  docs/images/ChangeAssigneeCommandUML.png
  docs/images/ChangeTaskStatusCommandUML.png
  docs/images/DeleteTaskCommandUML.png
  docs/images/SDforChangeAssignee.png
  docs/images/SDforChangeAssigneeCommandParser.png
  docs/images/UiClassDiagram.png
  docs/team/yash-chowdhary.adoc
  src/main/java/seedu/club/commons/core/Messages.java
  src/main/java/seedu/club/logic/commands/ChangeAssigneeCommand.java
  src/main/java/seedu/club/logic/commands/ChangeTaskStatusCommand.java
  src/main/java/seedu/club/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/club/logic/parser/AssignTaskCommandParser.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/model/member/Password.java
  src/main/java/seedu/club/model/member/Username.java
  src/main/java/seedu/club/model/task/Assignee.java
  src/main/java/seedu/club/model/task/Assignor.java
  src/main/java/seedu/club/model/task/Date.java
  src/main/java/seedu/club/model/task/TaskIsRelatedToMemberPredicate.java
  src/main/java/seedu/club/model/task/Time.java
  src/main/java/seedu/club/model/task/UniqueTaskList.java
  src/main/java/seedu/club/storage/XmlAdaptedTask.java
  src/main/java/seedu/club/ui/ModifiedTaskCard.java
  src/main/java/seedu/club/ui/TaskCard.java
  src/test/java/guitests/guihandles/TaskCardHandle.java
  src/test/java/guitests/guihandles/TaskListPanelHandle.java
  src/test/java/seedu/club/logic/commands/ChangeAssigneeCommandTest.java
  src/test/java/seedu/club/logic/commands/ChangeTaskStatusCommandTest.java
  src/test/java/seedu/club/logic/commands/CommandTestUtil.java
  src/test/java/seedu/club/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/club/logic/parser/AssignTaskCommandParserTest.java
  src/test/java/seedu/club/model/ClubBookTest.java
  src/test/java/seedu/club/model/member/PasswordTest.java
  src/test/java/seedu/club/model/member/UsernameTest.java
  src/test/java/seedu/club/storage/XmlAdaptedTaskTest.java
  src/test/java/seedu/club/testutil/TaskBuilder.java
  src/test/java/seedu/club/testutil/TypicalIndexes.java
  src/test/java/seedu/club/testutil/TypicalTasks.java
  src/test/java/seedu/club/ui/TaskCardTest.java
  src/test/java/seedu/club/ui/TaskListPanelTest.java
  src/test/java/seedu/club/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddTaskCommandSystemTest.java
Labels: code.cleanup, status.Ongoing

#233 Update image sizes in DG
  docs/DeveloperGuide.adoc
Labels: type.Documentation

#230 Select UI bug
  src/main/java/seedu/club/commons/events/ui/UpdateCurrentlyLogInMemberEvent.java
  src/main/java/seedu/club/commons/events/ui/UpdateSelectionPanelEvent.java
  src/main/java/seedu/club/logic/commands/ChangeProfilePhotoCommand.java
  src/main/java/seedu/club/logic/commands/DeleteCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/logic/commands/LogInCommand.java
  src/main/java/seedu/club/logic/commands/LogOutCommand.java
  src/main/java/seedu/club/logic/commands/RemoveProfilePhotoCommand.java
  src/main/java/seedu/club/logic/commands/UndoCommand.java
  src/main/java/seedu/club/ui/LogInMemberBox.java
  src/main/java/seedu/club/ui/MainWindow.java
  src/main/java/seedu/club/ui/MemberOverviewPanel.java
  src/main/resources/view/CurrentlyLogInMemberBox.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MemberDetailsPanel.fxml
  src/test/java/seedu/club/logic/commands/CompressCommandTest.java
  src/test/java/seedu/club/logic/commands/DecompressCommandTest.java
  src/test/java/seedu/club/logic/commands/HideResultsCommandTest.java
  src/test/java/seedu/club/logic/commands/SelectCommandTest.java
  src/test/java/seedu/club/logic/commands/ViewResultsCommandTest.java
Labels: status.readyToMerge

#234 Updates
  collated/functional/MuhdNurKamal.md
  collated/functional/amrut-prabhu.md
  collated/functional/th14thmusician.md
  collated/functional/yash-chowdhary.md
  collated/test/MuhdNurKamal.md
  collated/test/amrut-prabhu.md
  collated/test/th14thmusician.md
  collated/test/yash-chowdhary.md
  src/main/java/seedu/club/logic/commands/ChangeProfilePhotoCommand.java
  src/main/java/seedu/club/logic/commands/RemoveProfilePhotoCommand.java
  src/main/java/seedu/club/ui/LogInMemberBox.java
  src/main/java/seedu/club/ui/MemberCard.java
  src/main/java/seedu/club/ui/MemberOverviewPanel.java
  src/main/java/seedu/club/ui/TaskListPanel.java
  src/main/resources/view/CurrentlyLogInMemberBox.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MemberDetailsPanel.fxml
Labels: status.readyForReview, type.Code, type.fix

#237 Solve showing all list when editing and changing in filtered list and exceptions
  src/main/java/seedu/club/logic/commands/ChangeProfilePhotoCommand.java
  src/main/java/seedu/club/logic/commands/EditCommand.java
  src/main/java/seedu/club/model/ModelManager.java
  src/test/java/seedu/club/logic/commands/EditCommandTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: bug

#235 More cleanup
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/yash-chowdhary.adoc
  src/main/java/seedu/club/logic/commands/ClearCommand.java
  src/main/java/seedu/club/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/club/model/ClubBook.java
  src/main/java/seedu/club/model/ModelManager.java
  src/test/java/seedu/club/logic/commands/DeleteTaskCommandTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteTaskCommandSystemTest.java
Labels: status.Ongoing

#238 More Updates
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/invalid_CSV_format.png
  docs/team/amrut-prabhu.adoc
  src/main/java/seedu/club/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/club/logic/parser/ChangeProfilePhotoCommandParser.java
  src/main/java/seedu/club/logic/parser/ExportCommandParser.java
  src/main/java/seedu/club/logic/parser/ImportCommandParser.java
  src/main/java/seedu/club/logic/parser/ParserUtil.java
  src/main/java/seedu/club/model/member/ProfilePhoto.java
  src/main/java/seedu/club/storage/CsvClubBookStorage.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/club/logic/parser/ChangeProfilePhotoCommandParserTest.java
  src/test/java/seedu/club/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/club/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/club/storage/CsvClubBookStorageTest.java
Labels: status.readyForReview, type.Code, type.Documentation, type.fix

#236 cleanup
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/PollWithResults.png
  docs/images/PollWithoutResults.png
  docs/team/MuhdNurKamal.adoc
  src/main/java/seedu/club/ui/PollCard.java
  src/main/resources/view/AnswerListCard.fxml
  src/main/resources/view/PollListCard.fxml
  src/main/resources/view/RestrictedAnswerListCard.fxml
  src/main/resources/view/RestrictedPollListCard.fxml
Labels: kudos, status.readyForReview, type.Documentation

#240 Update documentation, portfolio and userguide.
  collated/functional/Song.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ChangePasswordUML.png
  docs/images/LogInCommandUML.png
  docs/images/SDChangePassword.png
  docs/images/SDLogIn.png
  docs/images/SDSignUp.png
  docs/images/SDforChangePasswordCommand.png
  docs/images/SDforLogInCommand.png
  docs/images/SDforSignUpCommand.png
  docs/images/SignUpCommandUML.png
  docs/team/th14thmusician.adoc
  dummy.csv
Labels: priority.high, status.readyForReview

#241 DG updates
  collated/functional/amrut-prabhu.md
  collated/test/amrut-prabhu.md
  docs/DeveloperGuide.adoc
  docs/diagrams/ChangeProfilePhotoCommandUML.pptx
  docs/diagrams/ExportCommandUML.pptx
  docs/diagrams/ImportCommandUML.pptx
  docs/diagrams/SDforExport.pptx
  docs/diagrams/SDforExportEventHandling.pptx
  docs/diagrams/SDforImport.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/ChangeProfilePhotoCommandUML.png
  docs/images/ExportCommandUML.png
  docs/images/ImportCommandUML.png
  docs/images/SDforExport.png
  docs/images/SDforExportEventHandling.png
  docs/images/SDforImport.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/team/amrut-prabhu.adoc
  src/main/java/seedu/club/commons/util/CsvUtil.java
  src/main/java/seedu/club/model/ModelManager.java
  src/main/java/seedu/club/storage/CsvClubBookStorage.java
  src/main/java/seedu/club/storage/CsvFileStorage.java
  src/main/java/seedu/club/storage/PhotoStorage.java
  src/main/java/seedu/club/storage/Storage.java
  src/main/java/seedu/club/storage/StorageManager.java
Labels: code.cleanup, priority.high, status.Ongoing, type.Documentation

#245 Portfolio update
  docs/team/MuhdNurKamal.adoc
Labels: status.readyToMerge, type.Documentation
